// Auth types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';
export const UPDATE_USER = 'UPDATE_USER';

// Disease detection types
export const DETECTION_REQUEST = 'DETECTION_REQUEST';
export const DETECTION_SUCCESS = 'DETECTION_SUCCESS';
export const DETECTION_FAILURE = 'DETECTION_FAILURE';
export const GET_DETECTION_HISTORY = 'GET_DETECTION_HISTORY';
export const ADD_DETECTION_TO_HISTORY = 'ADD_DETECTION_TO_HISTORY';
export const DELETE_DETECTION = 'DELETE_DETECTION';

// Advisory content types
export const FETCH_ADVISORY_CATEGORIES = 'FETCH_ADVISORY_CATEGORIES';
export const FETCH_ADVISORY_CONTENT = 'FETCH_ADVISORY_CONTENT';
export const SEARCH_ADVISORY = 'SEARCH_ADVISORY';
export const FETCH_FEATURED_CONTENT = 'FETCH_FEATURED_CONTENT';
export const TOGGLE_SAVE_CONTENT = 'TOGGLE_SAVE_CONTENT';

// Group types
export const FETCH_USER_GROUPS = 'FETCH_USER_GROUPS';
export const CREATE_GROUP = 'CREATE_GROUP';
export const JOIN_GROUP = 'JOIN_GROUP';
export const LEAVE_GROUP = 'LEAVE_GROUP';
export const FETCH_GROUP_MESSAGES = 'FETCH_GROUP_MESSAGES';
export const SEND_GROUP_MESSAGE = 'SEND_GROUP_MESSAGE';

// App settings types
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const UPDATE_NOTIFICATION_SETTINGS = 'UPDATE_NOTIFICATION_SETTINGS';
export const UPDATE_SYNC_SETTINGS = 'UPDATE_SYNC_SETTINGS';